// Copyright © 2026 北京祺智科技有限公司. All rights reserved.
// https://www.qzso.com/ · managecode@gmail.com

// One-line canvas preview per node type, derived from its config. Data-driven
// table extracted from Canvas's FlowNodeComponent.
const NODE_PREVIEW: Record<string, (c: Record<string, unknown>) => string> = {
  http: (c) => (c.url as string) || 'No URL set',
  agent: (c) => (c.model as string) || 'claude-sonnet-4-6',
  condition: (c) => c.field ? `if ${String(c.field)}` : 'No field set',
  approval: (_c) => 'Awaits human approval',
  map: (c) => c.items ? `map ${String(c.items)}` : 'No items set',
  filter: (c) => {
    if (!c.items) return 'No items set'
    const op = (c.operator as string) || 'exists'
    return c.field ? `${String(c.field)} ${op}${c.value ? ` ${String(c.value)}` : ''}` : 'No field set'
  },
  aggregate: (c) => {
    const op = (c.operation as string) || ''
    return op ? `${op}${c.field ? `(${String(c.field)})` : ''}` : 'No operation set'
  },
  sort: (c) => {
    const ord = (c.order as string) || 'asc'
    return c.field ? `${String(c.field)} ${ord}` : 'No field set'
  },
  transform: (c) => c.template ? 'template configured' : 'No template set',
  delay: (c) => {
    const s = c.seconds as number | undefined
    return s !== undefined ? `wait ${s}s` : 'No duration set'
  },
  sub_workflow: (c) => (c.workflow_id as string) || 'No workflow set',
  assert: (c) => c.condition ? `assert ${String(c.condition)}` : 'No condition set',
  catch: (c) => c.source ? `catch ${String(c.source)}` : 'Catches any error',
  fan_out: (_c) => 'Splits into parallel branches',
  fan_in: (_c) => 'Collects branch results',
  code: (c) => c.script ? String(c.script).split('\n')[0].slice(0, 40) : 'No script',
  slack: (c) => c.text ? String(c.text).slice(0, 40) : 'No message',
  email: (c) => c.to ? `to: ${String(c.to)}` : 'No recipient',
  rag: (c) => c.kb ? `kb: ${String(c.kb)}` : 'No knowledge base',
  rag_ingest: (c) => c.kb ? `kb: ${String(c.kb)}` : 'No knowledge base',
  custom: (c) => c.custom_node ? String(c.custom_node) : 'No custom node',
  openai: (c) => (c.model as string) || 'gpt-5.4-mini',
  gemini: (c) => (c.model as string) || 'gemini-2.5-flash',
  database: (c) => c.query ? String(c.query).split('\n')[0].slice(0, 40) : 'No query',
  extract: (c) => c.path ? `path: ${String(c.path)}` : 'No path set',
  merge: (_c) => 'Merges fields',
  loop: (c) => c.items ? `loop ${String(c.items)}` : 'No items set',
  graphql: (c) => c.url ? String(c.url).replace(/^https?:\/\//, '') : 'No URL set',
  validate: (c) => c.source ? `validate ${String(c.source)}` : 'No source set',
  note: (c) => (c.text as string) || 'Click to add note text',
  claude: (c) => (c.model as string) || 'claude-sonnet-4-6',
  github: (c) => c.endpoint ? `${String(c.method ?? 'GET')} ${String(c.endpoint)}` : 'No endpoint set',
  webhook: (c) => c.url ? String(c.url).replace(/^https?:\/\//, '') : 'No URL set',
  jira: (c) => c.endpoint ? `${String(c.method ?? 'GET')} ${String(c.endpoint)}` : 'No endpoint set',
  notion: (c) => c.endpoint ? `${String(c.method ?? 'GET')} ${String(c.endpoint)}` : 'No endpoint set',
  linear: (c) => c.query ? String(c.query).slice(0, 40) + (String(c.query).length > 40 ? '…' : '') : 'No query set',
  airtable: (c) => c.base_id && c.table ? `${String(c.base_id)}/${String(c.table)}` : 'No base/table set',
  for_each: (c) => c.workflow_id ? `→ ${String(c.workflow_id).slice(0, 20)}` : 'No workflow set',
  discord: (c) => c.content ? String(c.content).slice(0, 40) : 'No message content',
  teams: (c) => c.text ? String(c.text).slice(0, 40) : 'No message text',
  sheets: (c) => c.spreadsheet_id ? `${String(c.spreadsheet_id).slice(0, 20)} / ${String(c.range ?? 'Sheet1!A1')}` : 'No spreadsheet set',
  xml: (c) => c.source ? String(c.source).slice(0, 40) : 'No source set',
  yaml: (c) => `${String(c.mode ?? 'parse')} mode${c.source ? '' : ' — no source'}`,
  twilio: (c) => c.to ? `→ ${String(c.to)}` : 'No recipient set',
  stripe: (c) => c.endpoint ? `${String(c.method ?? 'GET')} ${String(c.endpoint)}` : 'No endpoint set',
  crypto: (c) => `${String(c.operation ?? 'sha256')}${c.source ? '' : ' — no source'}`,
  hubspot: (c) => c.endpoint ? `${String(c.method ?? 'GET')} ${String(c.endpoint)}` : 'No endpoint set',
  date: (c) => String(c.operation ?? 'now'),
  zendesk: (c) => c.endpoint ? `${String(c.subdomain ?? '?')}: ${String(c.endpoint)}` : 'No endpoint set',
  redis: (c) => c.url ? `${String(c.operation ?? 'get')} ${String(c.key ?? '')}` : 'No URL set',
  elasticsearch: (c) => c.url ? `${String(c.method ?? 'GET')} ${String(c.endpoint ?? '/_search')}` : 'No URL set',
  pagerduty: (c) => c.summary ? String(c.summary).slice(0, 40) : 'No summary set',
  handlebars: (c) => c.template ? String(c.template).slice(0, 40) : 'No template set',
  math: (c) => `${String(c.operation ?? 'add')}(${c.a ?? '?'}, ${c.b ?? '?'})`,
  array_utils: (c) => `${String(c.operation ?? 'chunk')}${c.source ? '' : ' — no source'}`,
  shopify: (c) => c.shop ? `${String(c.method ?? 'GET')} ${String(c.shop)}${String(c.endpoint ?? '/products.json')}` : 'No shop set',
  datadog: (c) => c.endpoint ? `${String(c.method ?? 'GET')} ${String(c.endpoint)}` : 'No endpoint set',
  salesforce: (c) => c.instance_url ? `${String(c.method ?? 'GET')} ${String(c.endpoint ?? '/services/data/v59.0/sobjects')}` : 'No instance URL',
  freshdesk: (c) => c.domain ? `${String(c.domain)}${String(c.endpoint ?? '')}` : 'No domain set',
  mailgun: (c) => c.to ? `→ ${String(c.to)}` : 'No recipient set',
  asana: (c) => c.endpoint ? `${String(c.method ?? 'GET')} ${String(c.endpoint)}` : 'No endpoint set',
  servicenow: (c) => c.instance ? `${String(c.instance)}${String(c.endpoint ?? '/api/now/table/incident')}` : 'No instance set',
  confluence: (c) => c.endpoint ? `${String(c.method ?? 'GET')} ${String(c.endpoint)}` : 'No endpoint set',
  bitbucket: (c) => c.endpoint ? `${String(c.method ?? 'GET')} ${String(c.endpoint)}` : 'No endpoint set',
  azure_devops: (c) => c.organization ? `${String(c.organization)}${c.project ? '/'+String(c.project) : ''}${String(c.endpoint ?? '')}` : 'No organization set',
  twitch: (c) => c.endpoint ? `${String(c.method ?? 'GET')} ${String(c.endpoint)}` : 'No endpoint set',
  figma: (c) => c.endpoint ? String(c.endpoint).slice(0, 40) : 'No endpoint set',
  dropbox: (c) => `${String(c.operation ?? 'list_folder')}${c.path ? ' '+String(c.path) : ''}`,
  cloudflare: (c) => c.endpoint ? `${String(c.method ?? 'GET')} ${String(c.endpoint)}` : 'No endpoint set',
  box: (c) => c.endpoint ? `${String(c.method ?? 'GET')} ${String(c.endpoint)}` : 'No endpoint set',
  okta: (c) => c.domain ? `${String(c.domain)}${String(c.endpoint ?? '')}` : 'No domain set',
  zoom: (c) => c.endpoint ? `${String(c.method ?? 'GET')} ${String(c.endpoint)}` : 'No endpoint set',
  spotify: (c) => c.endpoint ? `${String(c.method ?? 'GET')} ${String(c.endpoint)}` : 'No endpoint set',
  typeform: (c) => c.endpoint ? `${String(c.method ?? 'GET')} ${String(c.endpoint)}` : 'No endpoint set',
  webflow: (c) => c.endpoint ? `${String(c.method ?? 'GET')} ${String(c.endpoint)}` : 'No endpoint set',
  intercom: (c) => c.endpoint ? `${String(c.method ?? 'GET')} ${String(c.endpoint)}` : 'No endpoint set',
  pipedrive: (c) => c.endpoint ? `${String(c.method ?? 'GET')} ${String(c.endpoint)}` : 'No endpoint set',
  trello: (c) => c.endpoint ? `${String(c.method ?? 'GET')} ${String(c.endpoint)}` : 'No endpoint set',
  monday: (c) => c.query ? String(c.query).slice(0, 40) : 'No query set',
  clickup: (c) => c.endpoint ? `${String(c.method ?? 'GET')} ${String(c.endpoint)}` : 'No endpoint set',
  amplitude: (c) => `${String(c.operation ?? 'track')}`,
  mixpanel: (c) => `${String(c.operation ?? 'track')}`,
  segment: (c) => `${String(c.operation ?? 'track')}`,
  sendgrid: (c) => c.endpoint ? `${String(c.method ?? 'POST')} ${String(c.endpoint)}` : 'No endpoint set',
  braintree: (c) => c.endpoint ? `${String(c.environment ?? 'sandbox')} ${String(c.endpoint)}` : 'No endpoint set',
  paypal: (c) => c.endpoint ? `${String(c.environment ?? 'sandbox')} ${String(c.endpoint)}` : 'No endpoint set',
  razorpay: (c) => c.endpoint ? `${String(c.method ?? 'GET')} ${String(c.endpoint)}` : 'No endpoint set',
  firebase: (c) => c.endpoint ? `${String(c.service ?? 'firestore')} ${String(c.endpoint)}` : 'No endpoint set',
  supabase: (c) => c.endpoint ? `${String(c.method ?? 'GET')} ${String(c.endpoint)}` : 'No endpoint set',
  mailchimp: (c) => c.endpoint ? `${String(c.server ?? 'us1')} ${String(c.endpoint)}` : 'No endpoint set',
  activecampaign: (c) => c.endpoint ? `${String(c.method ?? 'GET')} ${String(c.endpoint)}` : 'No endpoint set',
  klaviyo: (c) => c.endpoint ? `${String(c.method ?? 'GET')} ${String(c.endpoint)}` : 'No endpoint set',
  resend: (c) => c.endpoint ? `${String(c.method ?? 'POST')} ${String(c.endpoint)}` : 'No endpoint set',
  contentful: (c) => c.endpoint ? `${String(c.api_type ?? 'delivery')} ${String(c.endpoint)}` : 'No endpoint set',
  algolia: (c) => c.endpoint ? String(c.endpoint) : 'No endpoint set',
  postmark: (c) => c.endpoint ? `${String(c.method ?? 'POST')} ${String(c.endpoint)}` : 'No endpoint set',
  vonage: (c) => `${String(c.operation ?? 'sms')}${c.to ? ' → '+String(c.to) : ''}`,
  telegram: (c) => c.chat_id ? `${String(c.operation ?? 'sendMessage')} → ${String(c.chat_id)}` : 'No chat ID set',
  replicate: (c) => c.version ? `${String(c.operation ?? 'run')} ${String(c.version).slice(0, 12)}…` : 'No model version',
  mistral: (c) => c.model ? `${String(c.operation ?? 'chat')} · ${String(c.model)}` : `${String(c.operation ?? 'chat')}`,
  whatsapp: (c) => c.to ? `${String(c.message_type ?? 'text')} → ${String(c.to)}` : 'No recipient',
  googledocs: (c) => c.document_id ? `${String(c.operation ?? 'get')} ${String(c.document_id).slice(0, 16)}…` : String(c.operation ?? 'get'),
  perplexity: (c) => c.model ? String(c.model) : 'sonar-small-online',
  cohere: (c) => `${String(c.operation ?? 'chat')}${c.model ? ' · '+String(c.model) : ''}`,
  googledrive: (c) => `${String(c.operation ?? 'list')}${c.file_id ? ' '+String(c.file_id).slice(0, 12)+'…' : ''}`,
  woocommerce: (c) => c.site_url ? `${String(c.method ?? 'GET')} ${String(c.endpoint ?? '/products')}` : 'No site URL',
  pinecone: (c) => `${String(c.operation ?? 'query')}${c.namespace ? ' ['+String(c.namespace)+']' : ''}`,
  togetherai: (c) => c.model ? `${String(c.operation ?? 'chat')} · ${String(c.model).split('/').pop()}` : String(c.operation ?? 'chat'),
  awss3: (c) => c.bucket ? `${String(c.operation ?? 'list')} ${String(c.bucket)}${c.key ? '/'+String(c.key) : ''}` : 'No bucket',
  huggingface: (c) => c.model ? `${String(c.operation ?? 'inference')} · ${String(c.model)}` : 'No model',
  groq: (c) => c.model ? `${String(c.operation ?? 'chat')} · ${String(c.model)}` : String(c.operation ?? 'chat'),
  openrouter: (c) => c.model ? `${String(c.operation ?? 'chat')} · ${String(c.model).split('/').pop()}` : String(c.operation ?? 'chat'),
  qdrant: (c) => c.collection ? `${String(c.operation ?? 'search')} [${String(c.collection)}]` : 'No collection',
  cloudinary: (c) => `${String(c.operation ?? 'upload')}${c.public_id ? ' · '+String(c.public_id) : ''}`,
  gcal: (c) => `${String(c.operation ?? 'list_events')}${c.calendar_id && c.calendar_id !== 'primary' ? ' ['+String(c.calendar_id)+']' : ''}`,
  docusign: (c) => `${String(c.operation ?? 'list_envelopes')}${c.account_id ? ' · '+String(c.account_id).slice(0, 8)+'…' : ''}`,
  xero: (c) => `${String(c.method ?? 'GET')} ${String(c.endpoint ?? '/Contacts')}`,
  calendly: (c) => String(c.operation ?? 'get_current_user'),
  apify: (c) => c.actor_id ? `${String(c.operation ?? 'run_actor')} · ${String(c.actor_id)}` : String(c.operation ?? 'run_actor'),
  ganalytics: (c) => c.property_id ? `${String(c.operation ?? 'run_report')} · ${String(c.property_id)}` : 'No property ID',
  neon: (c) => `${String(c.operation ?? 'list_projects')}${c.project_id ? ' · '+String(c.project_id).slice(0, 10)+'…' : ''}`,
  copper: (c) => `${String(c.operation ?? 'list')} ${String(c.resource ?? 'people')}`,
  azure_openai: (c) => c.deployment ? String(c.deployment) : 'deployment',
  grok: (c) => c.model ? String(c.model) : 'grok-4.3',
  ollama: (c) => c.model ? String(c.model) : 'llama3.2',
  weaviate: (c) => c.class ? `${String(c.operation ?? 'query')} [${String(c.class)}]` : String(c.operation ?? 'query'),
  chroma: (c) => c.collection ? `${String(c.operation ?? 'query')} [${String(c.collection)}]` : String(c.operation ?? 'query'),
  mongodb: (c) => c.collection ? `${String(c.operation ?? 'find')} [${String(c.collection)}]` : String(c.operation ?? 'find'),
  clickhouse: (c) => c.host ? 'SQL query' : 'No host',
  gcs: (c) => c.bucket ? `${String(c.operation ?? 'list')} ${String(c.bucket)}${c.object ? '/'+String(c.object) : ''}` : 'No bucket',
  azure_blob: (c) => c.container ? `${String(c.operation ?? 'list')} ${String(c.container)}${c.blob ? '/'+String(c.blob) : ''}` : 'No container',
  hash: (c) => String(c.operation ?? 'sha256'),
  jwt: (c) => `${String(c.operation ?? 'sign')} · ${String(c.algorithm ?? 'HS256')}`,
  vertex: (c) => String(c.model ?? 'gemini-1.5-flash'),
  sqs: (c) => `${String(c.operation ?? 'send')}${c.queue_url ? ' · '+String(c.queue_url).split('/').pop() : ''}`,
  sns: (c) => c.topic_arn ? `publish · ${String(c.topic_arn).split(':').pop()}` : 'publish',
  bedrock: (c) => c.model_id ? String(c.model_id) : 'No model',
  milvus: (c) => c.collection ? `${String(c.operation ?? 'search')} [${String(c.collection)}]` : String(c.operation ?? 'search'),
  kafka: (c) => c.topic ? `produce → ${String(c.topic)}` : 'No topic',
  rabbitmq: (c) => `${String(c.operation ?? 'publish')}${c.routing_key ? ' · '+String(c.routing_key) : ''}`,
  zip: (c) => String(c.operation ?? 'zip'),
  image: (c) => String(c.operation ?? 'metadata'),
  pdf_extract: (c) => c.pdf_base64 ? 'extract text' : 'No PDF',
  ocr: (c) => `ocr · ${String(c.lang ?? 'eng')}`,
  feishu: (c) => c.webhook_url ? 'bot · ' + String(c.msg_type ?? 'text') : 'app · ' + String(c.msg_type ?? 'text'),
  dingtalk: (c) => `${String(c.msg_type ?? 'text')}${c.secret ? ' · signed' : ''}`,
  wecom: (c) => String(c.msg_type ?? 'text'),
  embedding: (c) => String(c.model ?? 'text-embedding-3-small'),
  reranker: (c) => String(c.model ?? 'rerank-english-v3.0'),
  text_splitter: (c) => `chunk ${String(c.chunk_size ?? 1000)}/${String(c.chunk_overlap ?? 200)}`,
  structured_output: (c) => String(c.model ?? 'gpt-5.4-mini'),
  classifier: (c) => Array.isArray(c.categories) ? `${(c.categories as unknown[]).length} 类` : String(c.model ?? 'gpt-5.4-mini'),
  image_gen: (c) => String(c.model ?? 'dall-e-3'),
  video_gen: (c) => String(c.provider ?? 'seedance'),
  speech_to_text: (c) => String(c.model ?? 'whisper-1'),
  tts: (c) => `${String(c.model ?? 'tts-1')} · ${String(c.voice ?? 'alloy')}`,
  html_extract: (c) => c.selector ? `${String(c.extract ?? 'text')} · ${String(c.selector)}` : 'No selector',
  rss: (c) => c.url ? String(c.url).replace(/^https?:\/\//, '').slice(0, 28) : 'No URL',
  mysql: (c) => c.query ? 'SQL query' : 'No query',
  snowflake: (c) => c.account ? String(c.account) : 'No account',
  bigquery: (c) => c.project ? String(c.project) : 'No project',
  sqlserver: (c) => c.host ? `${String(c.host)}${c.database ? '/'+String(c.database) : ''}` : 'No host',
  ftp: (c) => c.host ? `${String(c.operation ?? 'list')} ${String(c.host)}` : 'No host',
  sftp: (c) => c.host ? `${String(c.operation ?? 'list')} ${String(c.host)}` : 'No host',
  ssh: (c) => c.host ? `ssh ${String(c.username ?? '')}@${String(c.host)}` : 'No host',
  imap: (c) => c.host ? `${String(c.operation ?? 'list_messages')} ${String(c.mailbox ?? 'INBOX')}` : 'No host',
  wait: (c) => String(c.mode ?? 'duration') === 'resume' ? 'until resumed' : (c.until ? `until ${String(c.until)}` : `${String(c.seconds ?? 0)}s`),
  deepseek: (c) => c.model ? String(c.model) : 'deepseek-v4-flash',
  qwen: (c) => c.model ? String(c.model) : 'qwen-max',
  zhipu: (c) => c.model ? String(c.model) : 'glm-4.6',
  moonshot: (c) => c.model ? String(c.model) : 'kimi-latest',
  doubao: (c) => c.endpoint_id ? String(c.endpoint_id) : 'No endpoint ID',
  minimax: (c) => c.model ? String(c.model) : 'MiniMax-Text-01',
  ernie: (c) => c.model ? String(c.model) : 'ernie-4.0-8k',
  hunyuan: (c) => c.model ? String(c.model) : 'hunyuan-turbos-latest',
}

export function nodePreview(nt: string | undefined, c: Record<string, unknown>): string {
  if (!nt) return ''
  const fn = NODE_PREVIEW[nt]
  return fn ? fn(c) : ''
}
